name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - staging
      - trying
    tags: '*'

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - "1.7"
          - "nightly"
        arch:
          - x64
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1

#name: CI
#
#on:
#  pull_request:
#    branches:
#      - master
#  push:
#    branches:
#      - master
#      - staging
#      - trying
#    tags: '*'
#
#jobs:
#  CI:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        julia-version: [‘1.6’, ‘1.7’, nightly]
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: julia-actions/setup-julia@v1
#        with:
#          version: ${{ matrix.julia-version }}
#          arch: ${{ matrix.arch }}
#       run: julia --color=yes --check-bounds=yes --project -e using Pkg; Pkg.test(coverage=true)
#      - uses: julia-actions/julia-buildpkg@latest
#      - uses: julia-actions/julia-runtest@latest
#      - uses: julia-actions/julia-processcoverage@v1
